// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8V9SbL6vTUCBMu2pBGpeqWamtYFW2SIE',
    appId: '1:1088747327129:web:0c9d1f159cbfdbb821f208',
    messagingSenderId: '1088747327129',
    projectId: 'e-shop-6e0b3',
    authDomain: 'e-shop-6e0b3.firebaseapp.com',
    storageBucket: 'e-shop-6e0b3.appspot.com',
    measurementId: 'G-984RWV8X9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aLPgD4g7B8hX1Rggd7kFlDoFEIA6Bb4',
    appId: '1:1088747327129:android:3f08d6b899295fa021f208',
    messagingSenderId: '1088747327129',
    projectId: 'e-shop-6e0b3',
    storageBucket: 'e-shop-6e0b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGw5jqqXeAdJyosSyqY0hVHrJkCvTaeAo',
    appId: '1:1088747327129:ios:532e62e379f7355c21f208',
    messagingSenderId: '1088747327129',
    projectId: 'e-shop-6e0b3',
    storageBucket: 'e-shop-6e0b3.appspot.com',
    iosClientId: '1088747327129-ag6bv6tr1a6nu99b266n13l6e4f18kfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShopweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGw5jqqXeAdJyosSyqY0hVHrJkCvTaeAo',
    appId: '1:1088747327129:ios:70b294a67fd9393d21f208',
    messagingSenderId: '1088747327129',
    projectId: 'e-shop-6e0b3',
    storageBucket: 'e-shop-6e0b3.appspot.com',
    iosClientId: '1088747327129-90d2eaunqaupf7tbv9mameii3algf32t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShopweb.RunnerTests',
  );
}
